version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The web UI
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  blog:
    image: pcuesta90/blog
    