# Generated by Django 3.2.8 on 2021-10-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
    ]
