# Generated by Django 3.2.8 on 2021-10-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211025_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('ip', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('user_agent', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('ip', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('user_agent', models.CharField(max_length=255)),
                ('view_count', models.IntegerField(default=0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
