# Generated by Django 3.2.8 on 2021-10-31 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211031_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ForeignKey(default='127.0.0.1', on_delete=django.db.models.deletion.CASCADE, to='posts.postview'),
            preserve_default=False,
        ),
    ]
